/*
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.ui.tests;

import com.google.inject.Injector;
import game.of.life.tasks.ui.internal.TasksActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TASKDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TasksActivator.getInstance().getInjector("game.of.life.tasks.TASKDSL");
	}

}
