/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL.impl;

import game.of.life.tasks.tASKDSL.TASKDSLPackage;
import game.of.life.tasks.tASKDSL.avAction;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>av Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.impl.avActionImpl#getBirth <em>Birth</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.impl.avActionImpl#getOvercrowd <em>Overcrowd</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.impl.avActionImpl#getXiso <em>Xiso</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.impl.avActionImpl#getSur <em>Sur</em>}</li>
 * </ul>
 *
 * @generated
 */
public class avActionImpl extends MinimalEObjectImpl.Container implements avAction
{
  /**
   * The default value of the '{@link #getBirth() <em>Birth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBirth()
   * @generated
   * @ordered
   */
  protected static final int BİRTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getBirth() <em>Birth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBirth()
   * @generated
   * @ordered
   */
  protected int birth = BİRTH_EDEFAULT;

  /**
   * The default value of the '{@link #getOvercrowd() <em>Overcrowd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOvercrowd()
   * @generated
   * @ordered
   */
  protected static final int OVERCROWD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getOvercrowd() <em>Overcrowd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOvercrowd()
   * @generated
   * @ordered
   */
  protected int overcrowd = OVERCROWD_EDEFAULT;

  /**
   * The default value of the '{@link #getXiso() <em>Xiso</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXiso()
   * @generated
   * @ordered
   */
  protected static final int XİSO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getXiso() <em>Xiso</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXiso()
   * @generated
   * @ordered
   */
  protected int xiso = XİSO_EDEFAULT;

  /**
   * The default value of the '{@link #getSur() <em>Sur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSur()
   * @generated
   * @ordered
   */
  protected static final int SUR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSur() <em>Sur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSur()
   * @generated
   * @ordered
   */
  protected int sur = SUR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected avActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TASKDSLPackage.Literals.AV_ACTİON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getBirth()
  {
    return birth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBirth(int newBirth)
  {
    int oldBirth = birth;
    birth = newBirth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TASKDSLPackage.AV_ACTİON__BİRTH, oldBirth, birth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getOvercrowd()
  {
    return overcrowd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOvercrowd(int newOvercrowd)
  {
    int oldOvercrowd = overcrowd;
    overcrowd = newOvercrowd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TASKDSLPackage.AV_ACTİON__OVERCROWD, oldOvercrowd, overcrowd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getXiso()
  {
    return xiso;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setXiso(int newXiso)
  {
    int oldXiso = xiso;
    xiso = newXiso;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TASKDSLPackage.AV_ACTİON__XİSO, oldXiso, xiso));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSur()
  {
    return sur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSur(int newSur)
  {
    int oldSur = sur;
    sur = newSur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TASKDSLPackage.AV_ACTİON__SUR, oldSur, sur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TASKDSLPackage.AV_ACTİON__BİRTH:
        return getBirth();
      case TASKDSLPackage.AV_ACTİON__OVERCROWD:
        return getOvercrowd();
      case TASKDSLPackage.AV_ACTİON__XİSO:
        return getXiso();
      case TASKDSLPackage.AV_ACTİON__SUR:
        return getSur();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TASKDSLPackage.AV_ACTİON__BİRTH:
        setBirth((Integer)newValue);
        return;
      case TASKDSLPackage.AV_ACTİON__OVERCROWD:
        setOvercrowd((Integer)newValue);
        return;
      case TASKDSLPackage.AV_ACTİON__XİSO:
        setXiso((Integer)newValue);
        return;
      case TASKDSLPackage.AV_ACTİON__SUR:
        setSur((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TASKDSLPackage.AV_ACTİON__BİRTH:
        setBirth(BİRTH_EDEFAULT);
        return;
      case TASKDSLPackage.AV_ACTİON__OVERCROWD:
        setOvercrowd(OVERCROWD_EDEFAULT);
        return;
      case TASKDSLPackage.AV_ACTİON__XİSO:
        setXiso(XİSO_EDEFAULT);
        return;
      case TASKDSLPackage.AV_ACTİON__SUR:
        setSur(SUR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TASKDSLPackage.AV_ACTİON__BİRTH:
        return birth != BİRTH_EDEFAULT;
      case TASKDSLPackage.AV_ACTİON__OVERCROWD:
        return overcrowd != OVERCROWD_EDEFAULT;
      case TASKDSLPackage.AV_ACTİON__XİSO:
        return xiso != XİSO_EDEFAULT;
      case TASKDSLPackage.AV_ACTİON__SUR:
        return sur != SUR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (birth: ");
    result.append(birth);
    result.append(", overcrowd: ");
    result.append(overcrowd);
    result.append(", xiso: ");
    result.append(xiso);
    result.append(", sur: ");
    result.append(sur);
    result.append(')');
    return result.toString();
  }

} //avActionImpl
