/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getName <em>Name</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getX <em>X</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getY <em>Y</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getNNo <em>NNo</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getS <em>S</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getAvAction <em>Av Action</em>}</li>
 * </ul>
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>NNo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>NNo</em>' attribute.
   * @see #setNNo(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_NNo()
   * @model
   * @generated
   */
  int getNNo();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getNNo <em>NNo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NNo</em>' attribute.
   * @see #getNNo()
   * @generated
   */
  void setNNo(int value);

  /**
   * Returns the value of the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' attribute.
   * @see #setS(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_S()
   * @model
   * @generated
   */
  int getS();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getS <em>S</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' attribute.
   * @see #getS()
   * @generated
   */
  void setS(int value);

  /**
   * Returns the value of the '<em><b>Av Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Av Action</em>' containment reference.
   * @see #setAvAction(avAction)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_AvAction()
   * @model containment="true"
   * @generated
   */
  avAction getAvAction();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getAvAction <em>Av Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Av Action</em>' containment reference.
   * @see #getAvAction()
   * @generated
   */
  void setAvAction(avAction value);

} // Cell
