/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getXC <em>XC</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getYC <em>YC</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Cell#getS <em>S</em>}</li>
 * </ul>
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>XC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>XC</em>' attribute.
   * @see #setXC(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_XC()
   * @model
   * @generated
   */
  int getXC();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getXC <em>XC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>XC</em>' attribute.
   * @see #getXC()
   * @generated
   */
  void setXC(int value);

  /**
   * Returns the value of the '<em><b>YC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>YC</em>' attribute.
   * @see #setYC(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_YC()
   * @model
   * @generated
   */
  int getYC();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getYC <em>YC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>YC</em>' attribute.
   * @see #getYC()
   * @generated
   */
  void setYC(int value);

  /**
   * Returns the value of the '<em><b>S</b></em>' attribute.
   * The literals are from the enumeration {@link game.of.life.tasks.tASKDSL.Status}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' attribute.
   * @see game.of.life.tasks.tASKDSL.Status
   * @see #setS(Status)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getCell_S()
   * @model
   * @generated
   */
  Status getS();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Cell#getS <em>S</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' attribute.
   * @see game.of.life.tasks.tASKDSL.Status
   * @see #getS()
   * @generated
   */
  void setS(Status value);

} // Cell
