/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
