/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.Game#getName <em>Name</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Game#getGameStatus <em>Game Status</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Game#getGridSize <em>Grid Size</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Game#getEvolutionRules <em>Evolution Rules</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Game#getStartGrid <em>Start Grid</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.Game#getAllCells <em>All Cells</em>}</li>
 * </ul>
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame()
 * @model
 * @generated
 */
public interface Game extends Model
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.Game#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Game Status</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.tasks.tASKDSL.GameStatus}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Game Status</em>' containment reference list.
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame_GameStatus()
   * @model containment="true"
   * @generated
   */
  EList<GameStatus> getGameStatus();

  /**
   * Returns the value of the '<em><b>Grid Size</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.tasks.tASKDSL.GridSize}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grid Size</em>' containment reference list.
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame_GridSize()
   * @model containment="true"
   * @generated
   */
  EList<GridSize> getGridSize();

  /**
   * Returns the value of the '<em><b>Evolution Rules</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.tasks.tASKDSL.evolutionRules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evolution Rules</em>' containment reference list.
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame_EvolutionRules()
   * @model containment="true"
   * @generated
   */
  EList<evolutionRules> getEvolutionRules();

  /**
   * Returns the value of the '<em><b>Start Grid</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.tasks.tASKDSL.StartGrid}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Grid</em>' containment reference list.
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame_StartGrid()
   * @model containment="true"
   * @generated
   */
  EList<StartGrid> getStartGrid();

  /**
   * Returns the value of the '<em><b>All Cells</b></em>' containment reference list.
   * The list contents are of type {@link game.of.life.tasks.tASKDSL.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All Cells</em>' containment reference list.
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGame_AllCells()
   * @model containment="true"
   * @generated
   */
  EList<Cell> getAllCells();

} // Game
