/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Status</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.GameStatus#getGs <em>Gs</em>}</li>
 * </ul>
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGameStatus()
 * @model
 * @generated
 */
public interface GameStatus extends EObject
{
  /**
   * Returns the value of the '<em><b>Gs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gs</em>' attribute.
   * @see #setGs(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGameStatus_Gs()
   * @model
   * @generated
   */
  int getGs();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.GameStatus#getGs <em>Gs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gs</em>' attribute.
   * @see #getGs()
   * @generated
   */
  void setGs(int value);

} // GameStatus
