/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.GridSize#getH <em>H</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.GridSize#getL <em>L</em>}</li>
 * </ul>
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGridSize()
 * @model
 * @generated
 */
public interface GridSize extends EObject
{
  /**
   * Returns the value of the '<em><b>H</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H</em>' attribute.
   * @see #setH(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGridSize_H()
   * @model
   * @generated
   */
  int getH();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.GridSize#getH <em>H</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H</em>' attribute.
   * @see #getH()
   * @generated
   */
  void setH(int value);

  /**
   * Returns the value of the '<em><b>L</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L</em>' attribute.
   * @see #setL(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getGridSize_L()
   * @model
   * @generated
   */
  int getL();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.GridSize#getL <em>L</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L</em>' attribute.
   * @see #getL()
   * @generated
   */
  void setL(int value);

} // GridSize
