/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
} // Model
