/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link game.of.life.tasks.tASKDSL.StartGrid#getXC <em>XC</em>}</li>
 *   <li>{@link game.of.life.tasks.tASKDSL.StartGrid#getYC <em>YC</em>}</li>
 * </ul>
 *
 * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getStartGrid()
 * @model
 * @generated
 */
public interface StartGrid extends EObject
{
  /**
   * Returns the value of the '<em><b>XC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>XC</em>' attribute.
   * @see #setXC(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getStartGrid_XC()
   * @model
   * @generated
   */
  int getXC();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.StartGrid#getXC <em>XC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>XC</em>' attribute.
   * @see #getXC()
   * @generated
   */
  void setXC(int value);

  /**
   * Returns the value of the '<em><b>YC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>YC</em>' attribute.
   * @see #setYC(int)
   * @see game.of.life.tasks.tASKDSL.TASKDSLPackage#getStartGrid_YC()
   * @model
   * @generated
   */
  int getYC();

  /**
   * Sets the value of the '{@link game.of.life.tasks.tASKDSL.StartGrid#getYC <em>YC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>YC</em>' attribute.
   * @see #getYC()
   * @generated
   */
  void setYC(int value);

} // StartGrid
