/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.tASKDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see game.of.life.tasks.tASKDSL.TASKDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TASKDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tASKDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.of.game/life/tasks/TASKDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tASKDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TASKDSLPackage eINSTANCE = game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.ModelImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.GameImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getGame()
   * @generated
   */
  int GAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Game Status</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GAME_STATUS = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Grid Size</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GRİD_SİZE = MODEL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Start Grid</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__START_GRİD = MODEL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>All Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__ALL_CELLS = MODEL_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = MODEL_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.GridSizeImpl <em>Grid Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.GridSizeImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getGridSize()
   * @generated
   */
  int GRİD_SİZE = 2;

  /**
   * The feature id for the '<em><b>H</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRİD_SİZE__H = 0;

  /**
   * The feature id for the '<em><b>L</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRİD_SİZE__L = 1;

  /**
   * The number of structural features of the '<em>Grid Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRİD_SİZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.GameStatusImpl <em>Game Status</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.GameStatusImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getGameStatus()
   * @generated
   */
  int GAME_STATUS = 3;

  /**
   * The feature id for the '<em><b>Gs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_STATUS__GS = 0;

  /**
   * The number of structural features of the '<em>Game Status</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_STATUS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.StartGridImpl <em>Start Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.StartGridImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getStartGrid()
   * @generated
   */
  int START_GRİD = 4;

  /**
   * The feature id for the '<em><b>XC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_GRİD__XC = 0;

  /**
   * The feature id for the '<em><b>YC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_GRİD__YC = 1;

  /**
   * The number of structural features of the '<em>Start Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_GRİD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.avActionImpl <em>av Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.avActionImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getavAction()
   * @generated
   */
  int AV_ACTİON = 5;

  /**
   * The feature id for the '<em><b>Birth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ACTİON__BİRTH = 0;

  /**
   * The feature id for the '<em><b>Overcrowd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ACTİON__OVERCROWD = 1;

  /**
   * The feature id for the '<em><b>Xiso</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ACTİON__XİSO = 2;

  /**
   * The feature id for the '<em><b>Sur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ACTİON__SUR = 3;

  /**
   * The number of structural features of the '<em>av Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ACTİON_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link game.of.life.tasks.tASKDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see game.of.life.tasks.tASKDSL.impl.CellImpl
   * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__NAME = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__Y = 2;

  /**
   * The feature id for the '<em><b>NNo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__NNO = 3;

  /**
   * The feature id for the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__S = 4;

  /**
   * The feature id for the '<em><b>Av Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__AV_ACTİON = 5;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 6;


  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see game.of.life.tasks.tASKDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see game.of.life.tasks.tASKDSL.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see game.of.life.tasks.tASKDSL.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the containment reference list '{@link game.of.life.tasks.tASKDSL.Game#getGameStatus <em>Game Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Game Status</em>'.
   * @see game.of.life.tasks.tASKDSL.Game#getGameStatus()
   * @see #getGame()
   * @generated
   */
  EReference getGame_GameStatus();

  /**
   * Returns the meta object for the containment reference list '{@link game.of.life.tasks.tASKDSL.Game#getGridSize <em>Grid Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Grid Size</em>'.
   * @see game.of.life.tasks.tASKDSL.Game#getGridSize()
   * @see #getGame()
   * @generated
   */
  EReference getGame_GridSize();

  /**
   * Returns the meta object for the containment reference list '{@link game.of.life.tasks.tASKDSL.Game#getStartGrid <em>Start Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Start Grid</em>'.
   * @see game.of.life.tasks.tASKDSL.Game#getStartGrid()
   * @see #getGame()
   * @generated
   */
  EReference getGame_StartGrid();

  /**
   * Returns the meta object for the containment reference list '{@link game.of.life.tasks.tASKDSL.Game#getAllCells <em>All Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>All Cells</em>'.
   * @see game.of.life.tasks.tASKDSL.Game#getAllCells()
   * @see #getGame()
   * @generated
   */
  EReference getGame_AllCells();

  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.GridSize <em>Grid Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid Size</em>'.
   * @see game.of.life.tasks.tASKDSL.GridSize
   * @generated
   */
  EClass getGridSize();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.GridSize#getH <em>H</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>H</em>'.
   * @see game.of.life.tasks.tASKDSL.GridSize#getH()
   * @see #getGridSize()
   * @generated
   */
  EAttribute getGridSize_H();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.GridSize#getL <em>L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>L</em>'.
   * @see game.of.life.tasks.tASKDSL.GridSize#getL()
   * @see #getGridSize()
   * @generated
   */
  EAttribute getGridSize_L();

  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.GameStatus <em>Game Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Status</em>'.
   * @see game.of.life.tasks.tASKDSL.GameStatus
   * @generated
   */
  EClass getGameStatus();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.GameStatus#getGs <em>Gs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gs</em>'.
   * @see game.of.life.tasks.tASKDSL.GameStatus#getGs()
   * @see #getGameStatus()
   * @generated
   */
  EAttribute getGameStatus_Gs();

  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.StartGrid <em>Start Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start Grid</em>'.
   * @see game.of.life.tasks.tASKDSL.StartGrid
   * @generated
   */
  EClass getStartGrid();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.StartGrid#getXC <em>XC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>XC</em>'.
   * @see game.of.life.tasks.tASKDSL.StartGrid#getXC()
   * @see #getStartGrid()
   * @generated
   */
  EAttribute getStartGrid_XC();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.StartGrid#getYC <em>YC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>YC</em>'.
   * @see game.of.life.tasks.tASKDSL.StartGrid#getYC()
   * @see #getStartGrid()
   * @generated
   */
  EAttribute getStartGrid_YC();

  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.avAction <em>av Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>av Action</em>'.
   * @see game.of.life.tasks.tASKDSL.avAction
   * @generated
   */
  EClass getavAction();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.avAction#getBirth <em>Birth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Birth</em>'.
   * @see game.of.life.tasks.tASKDSL.avAction#getBirth()
   * @see #getavAction()
   * @generated
   */
  EAttribute getavAction_Birth();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.avAction#getOvercrowd <em>Overcrowd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Overcrowd</em>'.
   * @see game.of.life.tasks.tASKDSL.avAction#getOvercrowd()
   * @see #getavAction()
   * @generated
   */
  EAttribute getavAction_Overcrowd();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.avAction#getXiso <em>Xiso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xiso</em>'.
   * @see game.of.life.tasks.tASKDSL.avAction#getXiso()
   * @see #getavAction()
   * @generated
   */
  EAttribute getavAction_Xiso();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.avAction#getSur <em>Sur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sur</em>'.
   * @see game.of.life.tasks.tASKDSL.avAction#getSur()
   * @see #getavAction()
   * @generated
   */
  EAttribute getavAction_Sur();

  /**
   * Returns the meta object for class '{@link game.of.life.tasks.tASKDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.Cell#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell#getName()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Name();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.Cell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell#getX()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_X();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.Cell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell#getY()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Y();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.Cell#getNNo <em>NNo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NNo</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell#getNNo()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_NNo();

  /**
   * Returns the meta object for the attribute '{@link game.of.life.tasks.tASKDSL.Cell#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>S</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell#getS()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_S();

  /**
   * Returns the meta object for the containment reference '{@link game.of.life.tasks.tASKDSL.Cell#getAvAction <em>Av Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Av Action</em>'.
   * @see game.of.life.tasks.tASKDSL.Cell#getAvAction()
   * @see #getCell()
   * @generated
   */
  EReference getCell_AvAction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TASKDSLFactory getTASKDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.ModelImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.GameImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Game Status</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GAME_STATUS = eINSTANCE.getGame_GameStatus();

    /**
     * The meta object literal for the '<em><b>Grid Size</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GRİD_SİZE = eINSTANCE.getGame_GridSize();

    /**
     * The meta object literal for the '<em><b>Start Grid</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__START_GRİD = eINSTANCE.getGame_StartGrid();

    /**
     * The meta object literal for the '<em><b>All Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__ALL_CELLS = eINSTANCE.getGame_AllCells();

    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.GridSizeImpl <em>Grid Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.GridSizeImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getGridSize()
     * @generated
     */
    EClass GRİD_SİZE = eINSTANCE.getGridSize();

    /**
     * The meta object literal for the '<em><b>H</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRİD_SİZE__H = eINSTANCE.getGridSize_H();

    /**
     * The meta object literal for the '<em><b>L</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRİD_SİZE__L = eINSTANCE.getGridSize_L();

    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.GameStatusImpl <em>Game Status</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.GameStatusImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getGameStatus()
     * @generated
     */
    EClass GAME_STATUS = eINSTANCE.getGameStatus();

    /**
     * The meta object literal for the '<em><b>Gs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_STATUS__GS = eINSTANCE.getGameStatus_Gs();

    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.StartGridImpl <em>Start Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.StartGridImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getStartGrid()
     * @generated
     */
    EClass START_GRİD = eINSTANCE.getStartGrid();

    /**
     * The meta object literal for the '<em><b>XC</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute START_GRİD__XC = eINSTANCE.getStartGrid_XC();

    /**
     * The meta object literal for the '<em><b>YC</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute START_GRİD__YC = eINSTANCE.getStartGrid_YC();

    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.avActionImpl <em>av Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.avActionImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getavAction()
     * @generated
     */
    EClass AV_ACTİON = eINSTANCE.getavAction();

    /**
     * The meta object literal for the '<em><b>Birth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ACTİON__BİRTH = eINSTANCE.getavAction_Birth();

    /**
     * The meta object literal for the '<em><b>Overcrowd</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ACTİON__OVERCROWD = eINSTANCE.getavAction_Overcrowd();

    /**
     * The meta object literal for the '<em><b>Xiso</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ACTİON__XİSO = eINSTANCE.getavAction_Xiso();

    /**
     * The meta object literal for the '<em><b>Sur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ACTİON__SUR = eINSTANCE.getavAction_Sur();

    /**
     * The meta object literal for the '{@link game.of.life.tasks.tASKDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see game.of.life.tasks.tASKDSL.impl.CellImpl
     * @see game.of.life.tasks.tASKDSL.impl.TASKDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__NAME = eINSTANCE.getCell_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__X = eINSTANCE.getCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__Y = eINSTANCE.getCell_Y();

    /**
     * The meta object literal for the '<em><b>NNo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__NNO = eINSTANCE.getCell_NNo();

    /**
     * The meta object literal for the '<em><b>S</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__S = eINSTANCE.getCell_S();

    /**
     * The meta object literal for the '<em><b>Av Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL__AV_ACTİON = eINSTANCE.getCell_AvAction();

  }

} //TASKDSLPackage
