/*
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TASKDSLScopeProvider extends AbstractTASKDSLScopeProvider {

}
