/*
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TASKDSLStandaloneSetup extends TASKDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TASKDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
