/*
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTASKDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(game.of.life.tasks.tASKDSL.TASKDSLPackage.eINSTANCE);
		return result;
	}
}
