/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TASKDSLIdeModule extends AbstractTASKDSLIdeModule {
}
