/*
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTASKDSLScopeProvider extends DelegatingScopeProvider {
}
