/**
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TASKDSLRuntimeModule extends AbstractTASKDSLRuntimeModule {
}
