/*
 * generated by Xtext 2.28.0
 */
package game.of.life.tasks.ui;

import com.google.inject.Injector;
import game.of.life.tasks.ui.internal.TasksActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TASKDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TasksActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TasksActivator activator = TasksActivator.getInstance();
		return activator != null ? activator.getInjector(TasksActivator.GAME_OF_LİFE_TASKS_TASKDSL) : null;
	}

}
